escalade-rails/config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, skip: [:registration, :password, :confirmation]
  resources :users, only: [:show, :index] do
    resources :sites
  end
end

escalade-rails/app/models/caddy_server_config_generator.rb
class CaddyServerConfigGenerator

  CONFIG_TEMPLATE = <<~EOS
    tlspages.adamvduke.com {
      root <%= File.join(serving_dir, "escalade", "escalade-rails", "public") %>
      tls adam.v.duke@gmail.com
      proxy / localhost:5000 {
        except /assets
      }
    }

    <% sites.each do |site| %>
    <%= site.domain_name %> {
      root <%= File.join(serving_dir, site.domain_name) %>
      tls <%= site.user.email  %>
    }

    <% end %>
  EOS

  def generate
    configuration = render_configuration
    write_configuration_file(configuration)
  end

  def render_configuration
    template = Erubis::Eruby.new(CONFIG_TEMPLATE)
    template.result(sites: Site.all.joins(:user),
                    serving_dir: serving_dir)
  end

  def write_configuration_file(configuration)
    File.open(caddyfile_path, "w") do |file|
      file.puts configuration
    end
  end

  def serving_dir
    ENV.fetch("CADDY_SERVING_DIR") { File.join("/", "srv") }
  end

  def caddyfile_path
    ENV.fetch("CADDYFILE_PATH") { File.join("tmp", "Caddyfile") }
  end
end

escalade-rails/app/models/caddyfile_generator.rb
class CaddyfileGenerator

  CONFIG_TEMPLATE = File.read(File.join(Rails.root, "lib", "caddy", "templates", "Caddyfile.erb")).freeze
  SITE_TEMPLATE = File.read(File.join(Rails.root, "lib", "caddy", "templates", "site_config.erb")).freeze

  def generate
    caddyfile = render_caddyfile
    write_caddyfile(caddyfile)

    FileUtils.mkdir(caddy_site_config_path) if !File.exist?(caddy_site_config_path)
    Site.all.each do |site|
      configuration = render_site_configuration(site)
      write_site_configuration(site, configuration)
    end
  end

  def render_caddyfile
    template = Erubis::Eruby.new(CONFIG_TEMPLATE)
    template.result(
      caddy_domain_name: caddy_domain_name,
      caddy_port: caddy_port,
      caddy_log_path: caddy_log_path,
      caddy_tls_email_address: caddy_tls_email_address,
      caddy_serving_dir: caddy_serving_dir,
      caddy_config_path: caddy_config_path,
      caddy_sites_path: caddy_sites_path,
      escalade_host: escalade_host,
      escalade_port: escalade_port,
      escalade_public_dir: escalade_public_dir
    )
  end

  def render_site_configuration(site)
    template = Erubis::Eruby.new(SITE_TEMPLATE)
    configuration = template.result(
      site_domain_name: site.domain_name,
      site_port: caddy_port,
      site_tls_email_address: site_tls_email_address(site),
      site_root: site_root(site),
      site_log_path: site_log_path(site)
    )
  end

  def write_site_configuration(site, configuration)
    File.open(site_configuration_file_path(site), "w") do |file|
      file.puts(configuration)
    end
  end

  def site_configuration_file_path(site)
    File.join(caddy_site_config_path, site.domain_name)
  end

  def caddy_site_config_path
    File.join(caddy_config_path, "sites")
  end

  def write_caddyfile(configuration)
    File.open(caddyfile_path, "w") do |file|
      file.puts configuration
    end
  end

  def caddy_config_path
    File.join(caddy_path, "config")
  end

  def site_root(site)
    File.join(caddy_serving_dir, site.domain_name)
  end

  def site_tls_email_address(site)
    Rails.env.production? ? site.user.email : caddy_tls_email_address
  end

  def site_log_path(site)
    "/dev/stdout"
  end

  def caddy_serving_dir
    ENV.fetch("CADDY_SERVING_DIR") { File.join("/", "srv", "sites") }
  end

  def caddyfile_path
    ENV.fetch("CADDYFILE_PATH") { File.join(caddy_config_path, "Caddyfile") }
  end

  def caddy_path
    ENV.fetch("CADDY_PATH") { File.join("/", "srv", "escalade", "caddy") }
  end

  def caddy_domain_name
    ENV.fetch("CADDY_DOMAIN_NAME") { "escalade" }
  end

  def caddy_port
    ENV.fetch("CADDY_PORT") { "80" }
  end

  def caddy_log_path
    ENV.fetch("CADDY_LOG_PATH") { "/dev/stdout" }
  end

  def caddy_tls_email_address
    ENV.fetch("CADDY_TLS_EMAIL_ADDRESS") { "off" }
  end

  def caddy_sites_path
    ENV.fetch("CADDY_SITES_PATH") { File.join(caddy_config_path, "sites", "*") }
  end

  def escalade_host
    ENV.fetch("ESCALADE_HOST") { "escalade-rails" }
  end

  def escalade_port
    ENV.fetch("ESCALADE_PORT") { "3000" }
  end

  def escalade_public_dir
    ENV.fetch("ESCALADE_PUBLIC_DIR") { File.join("/", "srv", "escalade-rails", "current", "public") }
  end
end

escalade-rails/app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
end

escalade-rails/app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :sites

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable #:registerable, :confirmable
end

escalade-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

escalade-rails/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!

  def index
    @sites = current_user.sites
  end

  def show
    @site = current_user.sites.find(params[:id])
  end
end

escalade-rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

escalade-rails/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

escalade-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

escalade-rails/app/views/layouts/_footer.html.haml
%footer
  .row
    .col-lg-12
      %p Copyright &copy; Your Website 2016

escalade-rails/app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

escalade-rails/app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

escalade-rails/app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  /%li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  /#%li= link_to 'Sign up', new_user_registration_path

- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Users', users_path

escalade-rails/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Escalade'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Escalade'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .container
        = yield
        = render 'layouts/footer'

escalade-rails/app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About

escalade-rails/app/views/sites/index.html.haml
%ul
  - @sites.each do |site|
    %li= site.vcs_url

escalade-rails/app/views/sites/show.html.haml
<h3>Sites</h3>
%p
  VCS URL:
  = link_to @site.vcs_url, @site.vcs_url if @site.vcs_url

escalade-rails/app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

escalade-rails/app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

escalade-rails/app/views/users/show.html.haml
%h3 User
%p
  Name:
  = @user.name if @user.name
%p
  Email:
  = @user.email if @user.email
- @user.sites.each do |site|
  %p= link_to site.vcs_url, user_site_path(@user, site)

escalade-rails/app/views/visitors/index.html.haml
.row
  .col-lg-12
    %h1.page-header Escalade
  .row
    .col-md-6.portfolio-item
      %a(href="#")
        %img.img-responsive{ src: image_path('700x400-placeholder.png'), alt: 'placeholder' }
      %h3
        %a(href="#")Site One
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
    .col-md-6.portfolio-item
      %a(href="#")
        %img.img-responsive{ src: image_path('700x400-placeholder.png'), alt: 'placeholder' }
      %h3
        %a(href="#")Site Two
      %p Lorem ipsum dolor sit Gamet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>